### ISSUE TITLE
Support node 18

### ISSUE THREAD

**Issue by elstgav** [natterstefan/plop-action-eslint#5]
# Feature Request

Node 18 is now the official LTS version of node, but the `package.json` restricts installation to node 14 or 16. Can you remove/relax the `engines` restriction?

**Comment by natterstefan** [comment]
Hi @elstgav,

yes for sure! I'll update the package asap. Thanks for asking.

**Comment by natterstefan** [comment]
Hi @elstgav,

I released a new version that relaxes the `engines` (added 18), and I removed `enginesStrict` as well. Let me know if you still have issues.
